### ISSUE TITLE
URL problem

### ISSUE THREAD

**Issue by balagab** [wolfgangimig/itol#12]
Hi there,

My problem is when trying to conifg the Issue Tracker I get the following error: 
![kepkivagas](https://cloud.githubusercontent.com/assets/7058332/6104417/9c543320-b04d-11e4-8ee8-59be376d6246.JPG)

My redmine's url is redirected from ip to host and from http to https, and have a valid cert. For url redericting I used the following:
"RewriteEngine On
  RewriteCond %{HTTP_HOST} !^myhostname.hu$
  RewriteRule /.\* https://myhostname.hu/ [R]
  RewriteCond %{HTTPS} !=on
  RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L"

Do you have any idea to solve it?

Thanks,
Gabor

**Comment by balagab** [comment]
If I turn of redirection it'sok however is it not possible to use with url redirection? Thanks

**Comment by wolfgangimig** [comment]
Hello Gabor,
Currently, URL redirection is not supported.

**Comment by marrngtn** [comment]
I assume this is the redirection problem:
![screen shot 05-01-15 at 05 24 pm](https://cloud.githubusercontent.com/assets/4671311/7437632/1afb79d6-f027-11e4-80bc-b9edf756ab3d.PNG)
I'm using a hosted version of Redmine with an SSL certificate

**Comment by wolfgangimig** [comment]
Yes, HTTP code 301 is used for redirection.

**Comment by wolfgangimig** [comment]
I have looked more closely on this redirection problems. 

@balagab your problem happends inside the SSL layer of Java. As I found [here](http://stackoverflow.com/questions/7615645/ssl-handshake-alert-unrecognized-name-error-since-upgrade-to-java-1-7-0), the error is shown because the server name used by Java does not match the  ServerName or ServerAlias defined in the Apache configuration. So please add a ServerName/ServerAlias to the http.conf file. Howerver, the next ITOL version 1.4 will set the system property mentioned in the article, so that Java will not check the server name anymore in SSL handshake.

@marrngtn The next version will follow redirected URLs.

 ITOL version 1.4 will be presumably available in the next few days.
