### ISSUE TITLE
Slow startup causes add-in to be disabled in Outlook

### ISSUE THREAD

**Issue by dan-sorion** [wolfgangimig/itol#17]
If the Redmine server process has gone to sleep, such as being left overnight, the first hits to it will be slow as the server starts it back up. While this can be adjusted in the server itself (although I'm still trying to figure out how!), steps could be taken in ITOL to mitigate this. I'm using Outlook 2013 where there is a 1000ms threshold for slow starting, and first thing in the morning for the past few days the ITOL add-in has been taking between 11 and 17 seconds to start which appears to be due to requesting the tracker data during the initialisation.

Would it be possible to have ITOL report a successful start to Outlook much earlier, and then request the tracker data in the background while Outlook is performing it's other startup processes? I realise this means that the issue tracker would not always be usable immediately upon starting Outlook, however would this not be better than having the plugin automatically disabled and require the user to have to keep enabling it every few days? There may be circumstances where the Redmine server instance is outside of the control of the person using ITOL and so adjusting process idle times to keep the server highly responsive is not an option.

Regards,

Dan

**Comment by wolfgangimig** [comment]
Hello Dan,
I assume that the startup time is slow because a Java  runtime has to be startet. Connecting to Redmine is performed in a background thread (as far as you installed one of the newer versions) and should not affect load time.
When the computer is started the first time after a longer pause, it is often slowed down by the virus scanner. This may cause the long load time of ITOL. 

In order to solve the problem, I suggest to start ITOL over the Autostart functionality of Windows. Then, ITOL will already be loaded and running before you start Outlook. 

The following lines show a BAT file, that starts ITOL and also ensures that it is enabled in Outlook:

```
pushd "%APPDATA%\..\Local\Issue Tracker for Microsoft Outlook 32bit"
REG add "HKCU\Software\Microsoft\Office\Outlook\Addins\ItolAddin.Class" /f /v "LoadBehavior" /t REG_DWORD /d 3
START "" "Issue Tracker for Microsoft Outlook 32bit.exe"
popd
```

Save this lines into a file with extension BAT in the Windows Autostart folder, e.g.:

```
C:\Users\Wolfgang\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\StartITOL.BAT
```

Please let me know, whether this suggestion works fine for you. If you gain positive experience with it, I will add it into the ITOL installation procedure.

Thanks.

Regards,
Wolfgang

**Comment by dan-sorion** [comment]
Hi Wolfgang,

That seems to have helped stop Outlook disabling the add-in. Previously I was seeing startup times anywhere from 10 seconds to 30 seconds, now they are logged as around 500ms to 800ms which is well within the Outlook startup threshold.

Regards,

Dan

**Comment by wolfgangimig** [comment]
Thank you, Dan, for this information. 
I will add this BAT to the next version.
Regards
