### ISSUE TITLE
Syncing redmine tickets with outlooks task view

### ISSUE THREAD

**Issue by hapm** [wolfgangimig/itol#20]
Would be a nice enhancement to have the redmine tickets sync with the outlook internal task feature, so that outlook reminds you on tasks added to redmine, and sync back changes made in outlook. I don't know it for sure but I think its possible with some work and it would be awesome as well. Synchronisation should be limitable to one or more saved redmine ticket querys. So everyone can customize the tickets to sync with redmines advanced query possibilities.

**Comment by matsbrucke** [comment]
I use http://www.fieldstonsoftware.com/software/gsyncit4/: it syncs with ToodleDo, parallel I use zapier to make a ToodleDo-Task out of a Redmine Ticket ;) (it works). See: http://zpr.io/7rEM

**Comment by wolfgangimig** [comment]
Thank you for this suggestion, hapm. 

Synchronizing tasks and tickets would be difficult. The user would expect that all the functions on the outlook toolbar also affected the redmine ticket. E.g. when closing the task, the ticket is also closed. When attaching a file to the task, the file is added to the ticket, too. When assigning a user, the ticket is assigned to the same user in redmine. When editing somewhere in the task, ... what should happen then? - depends on where the lines are added, deleted or modified. As far as I can see, it is very complex. However, maybe mbrucke's solution can handle all of this - or at least a valuable subset.

During research for answering this issue, I found out, that Redmine provides an Atom feed for a customized query and Outlook can subscribe this feed. This could be interesting for you. At the bottom of your issue list, you can find the link to the Atom feed at "Also available in: Atom". Go through the steps described [here](https://support.office.com/en-za/article/Subscribe-to-an-RSS-Feed-4f21fd86-fbcd-44e2-9f78-2013816f5214#__toc288635727) to create a folder in Outlook that lists a feed.

Unfortunately, ITOL is currently not able to show the feed items. But it should not be difficult. I will check this.

**Comment by sgissinger** [comment]
I just tested RedMine atom feed in Outlook, it's cool but not totally satisfying.
When you close an issue in RedMine, you also have to remove it manually from the Outlook RSS feed, it's not a sync tool.

Maybe you could create a new pane button **My Issues** next to **Issue Pane** or a tree item in mailbox like the RSS feed item.

It would be a list with the Issue title and the content pane would be the current **Issue Pane** in read-only mode and an additional link to open the issue in RedMine for modification purpose.

In fact...everything like the RSS feeds but with REST "live" sync support and RedMine issues metadatas.

_May I also propose you to rename **Issue Pane** to **Create an Issue**_

**Comment by wolfgangimig** [comment]
Thank you, sgissinger, for your suggestions.

Currently, I do not plan to spend much time providing an issue list ... with a configuration dialog where you can select the custom queries defined in Redmine etc. It sounds quite easy from the perspective of an user. Unfortunately, it would take many hours for me to realize.

Another Outlook function that might be of interest in this context is the possibility to create a folder entry that shows a website - described [here](https://support.microsoft.com/en-us/kb/287587). In our case, the homepage URL could be e.g. http://192.168.0.20/projects/outldd/issues?key=0c38a0bb4be20536a9266f0b705f6fdf5f9cf98e. Where by "outldd" is the project name and 0c38...8e is the API key. This folder shows the issues of the project "outldd" in an integrated browser window.

>  ... rename Issue Pane to Create an Issue

You can also modify existing issues in the "Issue Pane". Furthermore "Issue Pane" is a shorter text. That's why I think it should not be changed.

Best regards,
Wolfgang

**Comment by sgissinger** [comment]
Thanks for the suggestion about the web page.
My users open a very large amount of tab in there browsers and they tell me that they loose "too much time" to find the RedMine tab when they need it... :-)

I didn't realize that we could modify issues too, sorry

Best,
Sebastien
