### ISSUE TITLE
Can assign issue to role not configured for assignation

### ISSUE THREAD

**Issue by sgissinger** [wolfgangimig/itol#25]
In Redmine menu Administration > Roles and Permissions > Any Role, you can choose to allow issue assignation to the role or not.

In the **Issue Pane** > Properties, the **Assigned to** combobox displays every users of the project even if some of them have a role which is not configured to be assignable (like customers).

**Comment by wolfgangimig** [comment]
Unfortunately, I cannot get this information from the REST API. The call [roles](http://www.redmine.org/projects/redmine/wiki/Rest_Roles) just returns the role's permissions but not the options "Issues can be assigned to this role" and "Issues visibility".

In order to support this feature anyway, a variable definition was added to the IssueServiceImpl.js file of ITOL 1.4:

```
    // TODO: Names of roles whose members cannot be assignees.
    // Add one line for each role, that does NOT have checked the option 
    // "Issues can be assigned to this role". 
    // Format ... "rolename" : true, 
    var dontAssignIssuesToThisRoles = {
         "ExampleRoleNameNotAssignee" : true,
    };
```

Hence, if you want to exclude particular roles from the **Assign To** combobox, add the role names as described above.
