### ISSUE TITLE
Ticket History

### ISSUE THREAD

**Issue by matsbrucke** [wolfgangimig/itol#39]
Hi,

I use v 2.0 with Outlook 2016 and most of the things are fine ;). See the screenshot, the history field shows the login-window of the redmine server, after a login I can see the ticket, but it is only the website I see.

![image](https://cloud.githubusercontent.com/assets/10806821/12576393/a6fd3332-c413-11e5-9035-64a6c176b5d4.png)

**Comment by wolfgangimig** [comment]
Does it make a difference whether you login with user/pwd or API-key?

**Comment by matsbrucke** [comment]
After changing to user/pwd (it was API key before) and after entering the credentials in the history window it looks like the following screenshot after creating and modifing a ticket
![image](https://cloud.githubusercontent.com/assets/10806821/12579940/edada20e-c42b-11e5-8ac2-00fe327c889d.png)

You can scroll down to see the history in the window, but this is probably not, how it should work?

**Comment by wolfgangimig** [comment]
Hello mbrucke,
1. History view
   As far as I could find out, the Redmine API does not provide functions to read the change log of an issue. So I just placed an embedded browser on the HISTORY tab which shows the original Redmine issue page.
2. Extra login
   An extra login is necessary if you use user/password authentication. This is because the credentials cannot be passed to the embedded browser. 
   When you enter an API-Key, you should be able to see the history without an extra login. Unfortunately, there is a bug in IssueServiceImpl.js (see installation directory) in line 1857. As a quick workaround you can fix it yourself:

Line 1855ff:

```
 function getIssueHistoryUrl(issueId) {
   var ret = config.url + "/issues/" + issueId;
   if (config.apiKey) {                  // <-------- wrong: config.key, right: config.apiKey
     ret += "?key=" + config.apiKey;
   }
   return ret;
}
```

Kind regards,
Wolfgang

**Comment by matsbrucke** [comment]
ah ok, so this is the intended funcitonality ;).
