### ISSUE TITLE
Project/User List Enhancements

### ISSUE THREAD

**Issue by jonnsn** [wolfgangimig/itol#6]
The Project/User List is limited to 20 Items currently. I tried to edit the according variable in IssueServiceImpl.js (%AppData%\Local\JOA Issue Tracker for Microsoft Outlook\app) directly, but it did not seem to work this way.

Furthermore it would be very nice, if the list would be searchable I guess. Maybe the list could even provide some sort of autocomplete and fetch/show the list items according to the already entered data, instead of displaying the first x Records (how should one be able to reach Project 21 currently?).

_Note: I am just collecting some thoughts about enhancements here and maybe in following "issues" too. I really like the Idea of an Outlook Add-In and appreciate the already released work very much. Thanks for that!_

**Comment by wolfgangimig** [comment]
Thank you, jonnsn, for your valuable suggestions. 

As I started developing the addin, I didn't know whether anyone is interested in it. I didn't want to put much effort in something, that nobody finds useful. That's the main reason why I only provide a very simple solution for many use cases.

Yes, it would be very nice to have such a sophisticated autocomplete field. I tag your suggestion with the lable "enhancement". But I think, it need not to be realized immediately. 

After you have edited the IssueServiceImpl.js, in order to apply the changes, click the "Save" button in the configuration view (Backstage view, Outlook - File - Issue Tracker - Save). The script is re-loaded an a new connection is opened to Redmine.

Thus, if you increase the value in line 

```
var MAX_USERS = 20;
```

and click "Save" (or restart Outlook) you should be able to select more users per project.

Regards

**Comment by jonnsn** [comment]
Thank you for the explanation about the max_users variable. I will try that.

Of course I do not expect that the enhancement will be realized immediately - I just wanted it to be noted down.
I will also try to find some time to make a pull Request, though my java knowledge is a little bit "rusty".
Apart from this issue I will definitely have a deeper look at Joa if I find some time, it looks very useful to me!

**Comment by Sledav** [comment]
Hello!
I changed the value  MAX_USERS. Set to 40 and restart Outlook. I see only 25 users when creating a Issue, but in my project involved 36 users.

**Comment by jonnsn** [comment]
Well it works with the save button in my case.
Note that the 64 bit version-File is located under "%AppData%\Local\Issue Tracker for Microsoft Outlook 64bit\app"
