### ISSUE TITLE
[Feature proposal] create new Issues without an existing Mail

### ISSUE THREAD

**Issue by jonnsn** [wolfgangimig/itol#7]
I currently have a mail-Template in Outlooks Quicksteps for new Tickets (received by Redmine via IMap). Evertime I want to create a new Issue, I have to replace some "Markers" (like project-name or assigned-to) in the Mail to set those values correctly in Redmine.
With this Add-In this could be done much better with the according Gui-Fields - you don't even have to know the correct Markers and Values for Redmine anymore.
Currently one can create issues from existing mails - the text is prefilled with the mail text and the original message is appended. It would be nice if you could also create new Issues from a blank form if this is possible.
So it would be more like some of the currently available Desktop clients - but totally integrated in Outlook.

**Comment by wolfgangimig** [comment]
A "New Issue" button could be easily placed in the main toolbar of Oultook. When this button is clicked, a (modal?) dialog is shown that displays the "Issue Form" (the form shown in received mails in a task pane). Could this be a practicable way? Could it be confusing, that selected mails are ignored?

**Comment by matsbrucke** [comment]
Hi,

sounds good. What about an additional entry in the "right mouse button menu"? I use this a lot, because all the "Quicsteps" Outlook provides (make a calendar entry out of s.th.) and all the steps I builtfor myself are located there (e.g. send this mail to ToodleDo to make a todo out of it). Additionally many Addons (e.g. evernote) show an entry here. For evernote the entry says: "Make an evernote note out of this. This btw works also in the calender.

So, of course a "New Issue" button is needed in every view ;)

best

Mats

PS: I use ToodleDo for my personal "Getting Things Done" way of working, but we use Redmine in my company. At the moment I use ZAPIER to sync both, as Zapier generates a Toodle-Do Task, if someone gives me a redmine task and vice versa ;)

**Comment by wolfgangimig** [comment]
Hi Mats,
thank your for sharing your ideas and the interesting hints about ToodleDo and ZAPIER (looks like an ESB).

Indeed, the context menu is a standard place to add functionality. This applies e.g. to Windows explorer and Eclipse IDE too. My experience is, that context menus tent do get overloaded. The Eclipse context menu has more than 30 items. This is definitely too much. The Microsoft UI [guidelines](https://msdn.microsoft.com/en-us/library/windows/apps/hh465308.aspx) recommend to place not more than six commands in the context menu. According to this, Outlook's context menu is already full. That's why I would prefer to add the functions in the ribbon bar.

Outlook has two kinds of windows: explorer and inspector. An explorer shows a list of items (mails, tasks, calendar, notes, persons). A single item is displayed in an inspector (e.g a received mail). My suggestion is:
- If "New issue" is pressed in an explorer window (e. g. inbox), the "Issue Form" is opened in an independent dialog and all fields are blank. The context information (selected items in the explorer) is not used to fill the controls of the "Issue Form".
- If "New Issue" is pressed in an inspector window (e.g. received mail), the "Issue Form" is displayed as a task pane and is filled with context information (the mail subject and body). This already works for mail inspectors, it should be also realized for appointments and tasks. 
- The button caption "New Issue" is renamed to "Create issue" in inspector windows. This could help to distinguish the different actions.

Does this make sense?

**Comment by jonnsn** [comment]
+1 from me :)

**Comment by matsbrucke** [comment]
Hi,

Mh, for me it would make sense, if you would have two buttons: "new issue"
(something came to my mind and I want to capture it) and "Create issue":
create an issue with context.

Perhaps two buttons: "Blank Issue" and "Create issue", one is with context
an one is without? ;)

I would really love to also have the context info in the explorer window

best

Matthias

Von: Wolfgang Imig [mailto:notifications@github.com] 
Gesendet: Dienstag, 3. Februar 2015 23:22
An: wolfgangimig/itol
Cc: Matthias Brucke
Betreff: Re: [itol] [Feature proposal] create new Issues without an existing
Mail (#7)

Hi Mats,
thank your for sharing your ideas and the interesting hints about ToodleDo
and ZAPIER (looks like an ESB).

Indeed, the context menu is a standard place to add functionality. This
applies e.g. to Windows explorer and Eclipse IDE too. My experience is, that
context menus tent do get overloaded. The Eclipse context menu has more than
30 items. This is definitely too much. The Microsoft UI
https://msdn.microsoft.com/en-us/library/windows/apps/hh465308.aspx
guidelines recommend to place not more than six commands in the context
menu. According to this, Outlook's context menu is already full. That's why
I would prefer to add the functions in the ribbon bar.

Outlook has two kinds of windows: explorer and inspector. An explorer shows
a list of items (mails, tasks, calendar, notes, persons). A single item is
displayed in an inspector (e.g a received mail). My suggestion is:
- ```
      If "New issue" is pressed in an explorer window (e. g. inbox), the
  ```
  
  "Issue Form" is opened in an independent dialog and all fields are blank.
  The context information (selected items in the explorer) is not used to fill
  the controls of the "Issue Form".
- ```
      If "New Issue" is pressed in an inspector window (e.g. received
  ```
  
  mail), the "Issue Form" is displayed as a task pane and is filled with
  context information (the mail subject and body). This already works for mail
  inspectors, it should be also realized for appointments and tasks. 
- ```
      The button caption "New Issue" is renamed to "Create issue" in
  ```
  
  inspector windows. This could help to distinguish the different actions.

Does this make sense?


Reply to this email directly or
https://github.com/wolfgangimig/itol/issues/7#issuecomment-72748265 view
it on GitHub.
<https://github.com/notifications/beacon/AKTmJcesKwNB48JF1dmhZ_8BAgxiumgPks5
noUF4gaJpZM4Da8am.gif>
